version: "3.7"
volumes:
    data:
        name: ifttt
services:
    tester:
        image: ifttt_tester
        volumes:
            - ./tester:/usr/src/app
        ports:
            - "127.0.0.1:8079:8080"
        tty: true
        depends_on:
            - sensor
            - switch
            - server

    switch:
        image: ifttt_switch
        volumes:
            - ./switch:/usr/src/app
        ports:
            - "127.0.0.1:8080:8080"
        tty: true

    sensor:
        image: ifttt_sensor
        volumes:
            - ./sensor:/usr/src/app
        ports:
            - "127.0.0.1:8081:8080"
        deploy:
            mode: replicated
            replicas: 3
        tty: true

    server:
        image: ifttt_server
        volumes:
            - ./server:/usr/src/app
        ports:
            - "127.0.0.1:8082:8080"
        tty: true

