version: "3.7"
volumes:
    data:
        name: ifttt
    
services:
    switch:
        build:
            context: ./switch
            dockerfile: dockerfile
        volumes:
            - ./switch:/usr/src/app
        ports:
            - "8080"
        tty: true

    sensor:
        build:
            context: ./sensor
            dockerfile: dockerfile
        volumes:
            - ./sensor:/usr/src/app
        ports:
            - "8080"
        tty: true
        
    server:
        build:
            context: ./server
            dockerfile: dockerfile
        volumes:
            - ./server:/usr/src/app
        ports:
            - "127.0.0.1:8082:8080"
        tty: true

