FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN (apt-get update -y && \
	apt-get install -y cmake && \
	cd SEAL/native/src && \
	cmake . && \
	make && \
	cd ../.. && \
	cd native/examples && \
	cmake . && \
	make && \
	cd ../..)



CMD ["bash"]